# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    web_dir: "%kernel.root_dir%/../web"
    map_dir: "%kernel.root_dir%/../web/map"
    # output_dir: "%kernel.root_dir%/../web/output"
    cache_ttl: 600
    image_quality: 9
    image_compressed: 0
    image_logo: true
    cache_precision: 0
    cache_nodups: 0
    cache_stored_outside_project: 1

    color_background: 0xe0e0e0 # 0xffffff
    color_foreground: 0x000000
    color_clip_box: 0xff0000
    color_roi_box: 0xffff00
    color_logo: 0x30402080

services:
    #app.menu_builder:
    #    class: AppBundle\Menu\Builder
    #    arguments: ["@knp_menu.factory"]
     #   tags:
     #       - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
   #         - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }
